# Site settings
title: Mangal Prakash
email: mangalcrj@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Mangal Prakash is a Principal Scientist, AI/ML at Johnson & Johnson (Janssen R&D). His research interests span across computer vision and machine learning with particular emphasis on deep learning, graphical models, and deep probabilistic generative models.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mangalp.github.io/" # the base hostname & protocol for your site
twitter_username: mangal_prakash_
github_username: mangalp
google_scholar_user: gJmicvgAAAAJ

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag 